### ISSUE TITLE
403

### ISSUE THREAD

**Issue by catsAND** [samber/free_proxy_list#1]
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by samber** [comment]
The source list is currently sending a 403 body: http://txt.proxyspy.net/proxy.txt

Unfortunately, the status code is still 200 :-(

**Comment by samber** [comment]
@catsAND fixed by proxyspy.net
